safe_search = """
1. Child Pornography
Viewing content where persons under the age of 17 engage in sexually explicit activities is considered a sex crime. However, even just searching for child pornography, even if not to view it, can potentially get you arrested. When you perform the search, terms remain in your browser history or cache. This can be enough to have the police determine that you may have intended to watch child pornography. Officials may then conclude that you’re in possession of child pornography.
If you do download a video depicting someone under the age of 17 engaging in sexual activities (even accidentally), then may expect a call or visit from the police. Because law enforcement officials monitor certain keywords of all online searches, they can locate the IP address of your computer if they choose to make an arrest.
Be sure to avoid searching for anything related to child pornography. That way, it’s a visit you won’t have to worry about.
2. Torrenting
Streaming has become incredibly popular over the past decade. Illicit or unofficial streaming, known as “torrenting,” is a form of streaming that’s wildly popular. However, torrenting material that’s protected by copyright can land you in jail. Torrenting itself isn’t illegal, but viewing or sharing copyrighted material via torrent violates copyright laws. Not only you could face jail time, but also hefty fines from the copyright owner and you may be denied internet service.
Keep in mind that besides torrenting, unofficial streaming sites that show TV programs or films without permission may be illegal. If you’re caught as a user of one of those sites, you could also face jail time. Paying the extra few dollars to procure a legal streaming service seems a little less daunting when faced with years in jail and no internet usage.
3. Questionable Explosive Terms
With terrorism a constant threat to the world, cybersecurity investigators are keeping a close eye on anything related to terrorism or bomb-making. Officials are keeping such a close eye that innocent searches for backpacks and pressure cookers (or innocently clicking on “how bombs are made” because you’re curious) could wind up placing you on a potential terrorist watch list.
Not only will your internet searches become even more heavily watched, but you may just end up having a talk with some law enforcement officials about your intentions.
4. Hiring an Assassin
Although the “dark web” is a mystery to some, it does exist and is the criminal underworld of the internet. Not only can you find child pornography for sale, but you can also hire an assassin. Obviously, hiring an assassin to kill someone is illegal. This is precisely why you must express caution when performing such searches. Stay away from the dark web so that your innocent search for a crime novel or video game will keep you off a watchlist.
Although it seems stressful to put in additional thought as to what you’re searching for, it could save you some time explaining to the police or FBI the innocent intention behind your search items. Best not to search anything related to the items listed above at all, in the end."""
