HF_TOKEN = "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"
HUGGINGFACE_WRITE_KEY = "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"
hf_token = "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"
key = "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"
