[server]
headless = true
port = 8501
enableCORS = false

#[database]
# db_type = "postgresql"
# connection_string = "<your-database-connection-string>"

[huggingface]
hf_token = "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"
user_name = acecalisto3